# Generated by Django 4.2.4 on 2023-09-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delete', 'delete'), ('approved', 'approved')], default='pending', max_length=300),
        ),
    ]
